replicaCount: 1

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: example.local

config:
  enabled: false
  exampleValue: "default"

secret:
  enabled: false
  exampleValue: "changeme"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 1

podSecurityContext:
  enabled: false
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podAnnotations: {}

containerSecurityContext:
  enabled: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
