apiVersion: v1
kind: Service
metadata:
  name: {{ include "golden-path.fullname" . }}
  labels:
    {{- include "golden-path.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.containerPort.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort.name }}
      protocol: TCP
  selector:
    {{- include "golden-path.selectorLabels" . | nindent 4 }}
