apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: golden-path
  namespace: argocd
spec:
  description: Stage 4 golden-path workload boundary.
  sourceRepos:
    - https://github.com/Franklindot04/k8s-internal-developer-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: golden-path-demo
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: policy
      kind: PodDisruptionBudget
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
  orphanedResources:
    warn: true
