{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-chart.fullname" . }}
type: Opaque
stringData:
  exampleSecret: {{ .Values.secret.exampleValue | quote }}
{{- end }}
